//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobatako.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mobatako.Resources.ReferenceText", typeof(ReferenceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全運転お疲れ様でした。\n引き続く乗務を行う場合、車両を選択してください。.
        /// </summary>
        internal static string after_crewing_announce {
            get {
                return ResourceManager.GetString("after_crewing_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 車両を選択する.
        /// </summary>
        internal static string after_crewing_choose_vehicle_button {
            get {
                return ResourceManager.GetString("after_crewing_choose_vehicle_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全運転お疲れ様でした。乗り換える車両を選択してください。.
        /// </summary>
        internal static string after_crewing_transit_announce {
            get {
                return ResourceManager.GetString("after_crewing_transit_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務終了.
        /// </summary>
        internal static string after_crewing_work_state_label {
            get {
                return ResourceManager.GetString("after_crewing_work_state_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務中.
        /// </summary>
        internal static string after_crewing_work_state_label_of_transit {
            get {
                return ResourceManager.GetString("after_crewing_work_state_label_of_transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動乗車可能な車両を検索中.
        /// </summary>
        internal static string auto_search_vehicle_splash {
            get {
                return ResourceManager.GetString("auto_search_vehicle_splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モバたこでデジタコ連動するために Bletooth をオンにする必要があります。.
        /// </summary>
        internal static string blepermission_rationable {
            get {
                return ResourceManager.GetString("blepermission_rationable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停車しました。停車後の作業を選択してください。.
        /// </summary>
        internal static string choosing_stop_work_state {
            get {
                return ResourceManager.GetString("choosing_stop_work_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示条件.
        /// </summary>
        internal static string choosing_vehicle_change_condition_button {
            get {
                return ResourceManager.GetString("choosing_vehicle_change_condition_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 車両を再検索する.
        /// </summary>
        internal static string choosing_vehicle_change_research_button {
            get {
                return ResourceManager.GetString("choosing_vehicle_change_research_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示変更.
        /// </summary>
        internal static string choosing_vehicle_condition_button {
            get {
                return ResourceManager.GetString("choosing_vehicle_condition_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 車両名.
        /// </summary>
        internal static string choosing_vehicle_condition_car_label {
            get {
                return ResourceManager.GetString("choosing_vehicle_condition_car_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示条件.
        /// </summary>
        internal static string choosing_vehicle_condition_description {
            get {
                return ResourceManager.GetString("choosing_vehicle_condition_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗車可能な車両のみ表示.
        /// </summary>
        internal static string choosing_vehicle_condition_getoff_only_checkbox {
            get {
                return ResourceManager.GetString("choosing_vehicle_condition_getoff_only_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索する車両名を入力.
        /// </summary>
        internal static string choosing_vehicle_conditon_car_hint {
            get {
                return ResourceManager.GetString("choosing_vehicle_conditon_car_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗車中.
        /// </summary>
        internal static string choosing_vehicle_is_riding {
            get {
                return ResourceManager.GetString("choosing_vehicle_is_riding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索中です.
        /// </summary>
        internal static string choosing_vehicle_progress_description {
            get {
                return ResourceManager.GetString("choosing_vehicle_progress_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗車する車両を選択してください。.
        /// </summary>
        internal static string choosing_vehicle_screen_label {
            get {
                return ResourceManager.GetString("choosing_vehicle_screen_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string cloudDebugFeature {
            get {
                return ResourceManager.GetString("cloudDebugFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string db_name {
            get {
                return ResourceManager.GetString("db_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string digitachoFeature {
            get {
                return ResourceManager.GetString("digitachoFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実車空車確認.
        /// </summary>
        internal static string emp_load_confirm {
            get {
                return ResourceManager.GetString("emp_load_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空車にしない.
        /// </summary>
        internal static string emp_load_confirm_cancel {
            get {
                return ResourceManager.GetString("emp_load_confirm_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業変更に伴い、空車にしますか？.
        /// </summary>
        internal static string emp_load_confirm_description {
            get {
                return ResourceManager.GetString("emp_load_confirm_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空車にする.
        /// </summary>
        internal static string emp_load_confirm_ok {
            get {
                return ResourceManager.GetString("emp_load_confirm_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string end_crewing_cancel_button {
            get {
                return ResourceManager.GetString("end_crewing_cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to の運行を終了しますか？.
        /// </summary>
        internal static string end_crewing_description {
            get {
                return ResourceManager.GetString("end_crewing_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string end_crewing_dialog_cancel {
            get {
                return ResourceManager.GetString("end_crewing_dialog_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務終了理由を選択してください.
        /// </summary>
        internal static string end_crewing_dialog_description {
            get {
                return ResourceManager.GetString("end_crewing_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帰庫.
        /// </summary>
        internal static string end_crewing_dialog_leaving {
            get {
                return ResourceManager.GetString("end_crewing_dialog_leaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宿泊.
        /// </summary>
        internal static string end_crewing_dialog_loading {
            get {
                return ResourceManager.GetString("end_crewing_dialog_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務終了する.
        /// </summary>
        internal static string end_crewing_end_crewing_button {
            get {
                return ResourceManager.GetString("end_crewing_end_crewing_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動乗車に失敗しました。手動で車両を選択してください。.
        /// </summary>
        internal static string error_autoriding_description {
            get {
                return ResourceManager.GetString("error_autoriding_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bletooth　設定失敗.
        /// </summary>
        internal static string error_ble_disabled {
            get {
                return ResourceManager.GetString("error_ble_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bletooth設定が有効になっているか確認してから起動して下さい。.
        /// </summary>
        internal static string error_ble_disabled_description {
            get {
                return ResourceManager.GetString("error_ble_disabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジたことの接続が切断になりました。エンジンoff/onもしくはモバたこアプリを再起動して接続再開でしてください。.
        /// </summary>
        internal static string error_ble_disconnect {
            get {
                return ResourceManager.GetString("error_ble_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string error_ble_disconnect_ok {
            get {
                return ResourceManager.GetString("error_ble_disconnect_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再起動.
        /// </summary>
        internal static string error_ble_disconnect_reboot {
            get {
                return ResourceManager.GetString("error_ble_disconnect_reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーとの通信が出来ません.
        /// </summary>
        internal static string error_connection_fail {
            get {
                return ResourceManager.GetString("error_connection_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在、サーバーと通信できません。しばらくしてから起動して下さい。.
        /// </summary>
        internal static string error_connection_fail_description {
            get {
                return ResourceManager.GetString("error_connection_fail_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務終了失敗.
        /// </summary>
        internal static string error_end_crewing {
            get {
                return ResourceManager.GetString("error_end_crewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務終了処理に失敗しました。通信状況を確認してから再度乗務終了をしてください。.
        /// </summary>
        internal static string error_end_crewing_description {
            get {
                return ResourceManager.GetString("error_end_crewing_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string error_end_crewing_wo_tachodata_confirm_cancel_label {
            get {
                return ResourceManager.GetString("error_end_crewing_wo_tachodata_confirm_cancel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジタコデータが日報に反映されません。乗務を終了しますか？.
        /// </summary>
        internal static string error_end_crewing_wo_tachodata_confirm_description {
            get {
                return ResourceManager.GetString("error_end_crewing_wo_tachodata_confirm_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string error_end_crewing_wo_tachodata_confirm_ok_label {
            get {
                return ResourceManager.GetString("error_end_crewing_wo_tachodata_confirm_ok_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内部処理失敗.
        /// </summary>
        internal static string error_internal {
            get {
                return ResourceManager.GetString("error_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内部処理で異常が発生しました。ログイン画面に戻ります。.
        /// </summary>
        internal static string error_internal_description {
            get {
                return ResourceManager.GetString("error_internal_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインエラー.
        /// </summary>
        internal static string error_login_fail {
            get {
                return ResourceManager.GetString("error_login_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインに失敗しました。ログインID・パスワードを再度確認してからログインして下さい。.
        /// </summary>
        internal static string error_login_fail_description {
            get {
                return ResourceManager.GetString("error_login_fail_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインに失敗しました。IDとパスワードを確認して下さい。.
        /// </summary>
        internal static string error_login_fail_message {
            get {
                return ResourceManager.GetString("error_login_fail_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーコード＠企業団体コード　の形式で入力して下さい。.
        /// </summary>
        internal static string error_login_without_company_code {
            get {
                return ResourceManager.GetString("error_login_without_company_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC が有効になっていません。設定画面で有効にしてください。.
        /// </summary>
        internal static string error_nfc_setting {
            get {
                return ResourceManager.GetString("error_nfc_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジタコとの通信に失敗しました。失敗が続く場合は、バックアップ用SDカード用いて運行記録を取得してください。.
        /// </summary>
        internal static string error_tacho_detail {
            get {
                return ResourceManager.GetString("error_tacho_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務終了.
        /// </summary>
        internal static string error_tacho_end_button_label {
            get {
                return ResourceManager.GetString("error_tacho_end_button_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再接続.
        /// </summary>
        internal static string error_tacho_retry_button_label {
            get {
                return ResourceManager.GetString("error_tacho_retry_button_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デジタコ連動失敗.
        /// </summary>
        internal static string error_tacho_title {
            get {
                return ResourceManager.GetString("error_tacho_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務降車失敗.
        /// </summary>
        internal static string error_transit_failed {
            get {
                return ResourceManager.GetString("error_transit_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗換降車に失敗しました。しばらくして操作するか管理者へご連絡ください。.
        /// </summary>
        internal static string error_transit_failed_description {
            get {
                return ResourceManager.GetString("error_transit_failed_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初回時のみ再起動が必要です。\n再起動ボタンを押してアプリを再起動してください。.
        /// </summary>
        internal static string first_reboot_dialog_description {
            get {
                return ResourceManager.GetString("first_reboot_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初回再起動確認.
        /// </summary>
        internal static string first_reboot_dialog_title {
            get {
                return ResourceManager.GetString("first_reboot_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続中.
        /// </summary>
        internal static string home_digitacho_connected {
            get {
                return ResourceManager.GetString("home_digitacho_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非接続.
        /// </summary>
        internal static string home_digitacho_disconnected {
            get {
                return ResourceManager.GetString("home_digitacho_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string input_refuel_dialog_close_button {
            get {
                return ResourceManager.GetString("input_refuel_dialog_close_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信.
        /// </summary>
        internal static string input_refuel_dialog_send_button {
            get {
                return ResourceManager.GetString("input_refuel_dialog_send_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 給油量を入力.
        /// </summary>
        internal static string input_refuel_dialog_title {
            get {
                return ResourceManager.GetString("input_refuel_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインする.
        /// </summary>
        internal static string login_btn_login {
            get {
                return ResourceManager.GetString("login_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン情報を保持する.
        /// </summary>
        internal static string login_check_save_login {
            get {
                return ResourceManager.GetString("login_check_save_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを表示する.
        /// </summary>
        internal static string login_check_view_password {
            get {
                return ResourceManager.GetString("login_check_view_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo image.
        /// </summary>
        internal static string login_desc_logo {
            get {
                return ResourceManager.GetString("login_desc_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password icon.
        /// </summary>
        internal static string login_desc_password_icon {
            get {
                return ResourceManager.GetString("login_desc_password_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user icon.
        /// </summary>
        internal static string login_desc_user_icon {
            get {
                return ResourceManager.GetString("login_desc_user_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインID.
        /// </summary>
        internal static string login_user_id_hint {
            get {
                return ResourceManager.GetString("login_user_id_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        internal static string login_user_pw_hint {
            get {
                return ResourceManager.GetString("login_user_pw_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モバたこ位置情報をバックグラウンドで送信します。クラウド管理アプリで位置情報を表示する為に必要な情報ですので、直後に表示される許可ダイアログで「常に許可」を選択してください。.
        /// </summary>
        internal static string permission_announce_background_gps {
            get {
                return ResourceManager.GetString("permission_announce_background_gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置情報アクセスについて.
        /// </summary>
        internal static string permission_announce_background_gps_title {
            get {
                return ResourceManager.GetString("permission_announce_background_gps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置情報はモバたこで必要な機能です。設定画面で権限を追加して下さい。.
        /// </summary>
        internal static string permission_error_description {
            get {
                return ResourceManager.GetString("permission_error_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string permission_ok {
            get {
                return ResourceManager.GetString("permission_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モバたこで位置情報を取得するために必要な権限です。.
        /// </summary>
        internal static string permission_rationable {
            get {
                return ResourceManager.GetString("permission_rationable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定画面を開く.
        /// </summary>
        internal static string permission_setting {
            get {
                return ResourceManager.GetString("permission_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string refuel_dialog_close_button {
            get {
                return ResourceManager.GetString("refuel_dialog_close_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 給油所を選択.
        /// </summary>
        internal static string refuel_dialog_title {
            get {
                return ResourceManager.GetString("refuel_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ送信中・・・\n車両の電源は切らないでください。.
        /// </summary>
        internal static string sending_tacho_splash_description {
            get {
                return ResourceManager.GetString("sending_tacho_splash_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string server_api_key {
            get {
                return ResourceManager.GetString("server_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALREADY_REQUESTED_PERMISSION.
        /// </summary>
        internal static string shared_already_invoked_permission_request {
            get {
                return ResourceManager.GetString("shared_already_invoked_permission_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string speed_warning_dialog_close_button {
            get {
                return ResourceManager.GetString("speed_warning_dialog_close_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スピードに注意してください.
        /// </summary>
        internal static string speed_warning_dialog_description {
            get {
                return ResourceManager.GetString("speed_warning_dialog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度注意.
        /// </summary>
        internal static string speed_warning_dialog_title {
            get {
                return ResourceManager.GetString("speed_warning_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起動しています。.
        /// </summary>
        internal static string splash_announce {
            get {
                return ResourceManager.GetString("splash_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo image.
        /// </summary>
        internal static string splash_desc_logo {
            get {
                return ResourceManager.GetString("splash_desc_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to で乗務を開始しますか？.
        /// </summary>
        internal static string start_crewing_announcement {
            get {
                return ResourceManager.GetString("start_crewing_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to に乗り換えますか？.
        /// </summary>
        internal static string start_crewing_by_transit_announce {
            get {
                return ResourceManager.GetString("start_crewing_by_transit_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string start_crewing_by_transit_cancel_button {
            get {
                return ResourceManager.GetString("start_crewing_by_transit_cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string start_crewing_cancel_button {
            get {
                return ResourceManager.GetString("start_crewing_cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務開始中です。お待ちください。.
        /// </summary>
        internal static string start_crewing_progress_description {
            get {
                return ResourceManager.GetString("start_crewing_progress_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗務開始する.
        /// </summary>
        internal static string start_crewing_start_button {
            get {
                return ResourceManager.GetString("start_crewing_start_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗換する.
        /// </summary>
        internal static string start_crewing_start_by_transit_button {
            get {
                return ResourceManager.GetString("start_crewing_start_by_transit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 降車後の作業を選択してください。.
        /// </summary>
        internal static string transit_vehicle_choose_dialog_announce {
            get {
                return ResourceManager.GetString("transit_vehicle_choose_dialog_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string transit_vehicle_choose_work_dialog_cancel_button {
            get {
                return ResourceManager.GetString("transit_vehicle_choose_work_dialog_cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 降車.
        /// </summary>
        internal static string transit_vehicle_choose_work_dialog_getoff_button {
            get {
                return ResourceManager.GetString("transit_vehicle_choose_work_dialog_getoff_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロジたこと接続できません。.
        /// </summary>
        internal static string warn_disable_logitacho {
            get {
                return ResourceManager.GetString("warn_disable_logitacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        internal static string warn_disable_logitacho_cancel {
            get {
                return ResourceManager.GetString("warn_disable_logitacho_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロジたことの接続に失敗したため、運行記録はSDカードより取得してください。.
        /// </summary>
        internal static string warn_disable_logitacho_description {
            get {
                return ResourceManager.GetString("warn_disable_logitacho_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非接続.
        /// </summary>
        internal static string warn_disable_logitacho_start {
            get {
                return ResourceManager.GetString("warn_disable_logitacho_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再起動.
        /// </summary>
        internal static string warn_disable_logitacho_terminate {
            get {
                return ResourceManager.GetString("warn_disable_logitacho_terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「戻る」を押して再度車両を押してください。\n警告が続く場合は「再起動」を押してください。\nロジたこと非接続で運行する場合は「非接続」を押してください。但し、この場合はロジたこのデータは取得できません。.
        /// </summary>
        internal static string warn_disable_logitcho_question {
            get {
                return ResourceManager.GetString("warn_disable_logitcho_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC が有効になっていません。NFC を利用した自動乗車をご利用する場合は設定画面で有効にしてください。.
        /// </summary>
        internal static string warn_nfc_setting {
            get {
                return ResourceManager.GetString("warn_nfc_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string web_api_base_url {
            get {
                return ResourceManager.GetString("web_api_base_url", resourceCulture);
            }
        }
    }
}
